name: "Weekly Report"
description: Weekly activity log
title: "[WEEK] Week <number or date range>"
labels: ["weekly-log"]

body:
  - type: textarea
    id: highlights
    attributes:
      label: Key Highlights
      placeholder: "Example: OpenLane installed, first SkyWater 130 nm design synthesized"

  - type: textarea
    id: progress
    attributes:
      label: Detailed Progress
      placeholder: "- Adjusted Dockerfile\n- Drafted Migen tutorial\n- FSM demo running on Basys-3"

  - type: textarea
    id: blockers
    attributes:
      label: Blockers / Challenges
      placeholder: "Example: Library cell error, pending professor’s feedback"

  - type: textarea
    id: next
    attributes:
      label: Next Steps
      placeholder: "Example: Prepare live demo for meeting, record tutorial on Windows"

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      placeholder: "Ideas, reflections, or reminders for the week"
