name: "Weekly Report"
description: Informe de actividades semanales
title: "[WEEK] Semana <número o rango de fechas>"
labels: ["weekly-log"]

body:
  - type: textarea
    id: highlights
    attributes:
      label: Logros principales
      placeholder: "Ejemplo: Instalación de OpenLane, primer diseño con SkyWater 130 nm sintetizado"

  - type: textarea
    id: progress
    attributes:
      label: Avances detallados
      placeholder: "- Dockerfile ajustado\n- Tutorial de Migen en borrador\n- Demo de FSM corriendo en Basys-3"

  - type: textarea
    id: blockers
    attributes:
      label: Bloqueos o dificultades
      placeholder: "Ejemplo: Error en librería de celdas, pendiente revisar con profesor"

  - type: textarea
    id: next
    attributes:
      label: Próximos pasos
      placeholder: "Ejemplo: Preparar demo en vivo para llamada con el profesor, grabar tutorial en Windows"

  - type: textarea
    id: notes
    attributes:
      label: Notas adicionales
      placeholder: "Ideas, reflexiones o recordatorios de la semana"
